# Generated by Django 4.2.7 on 2023-11-28 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_pdf',
        ),
    ]
