# Generated by Django 4.2.7 on 2023-11-28 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_product_product_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='images/default.jpg', null=True, upload_to='images/'),
        ),
    ]
