# Generated by Django 4.2.7 on 2023-11-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_product_product_pdf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=40)),
                ('member_role', models.CharField(choices=[('web_admin', 'Web Admin'), ('content_manager', 'Content Manager'), ('web_developer', 'Web Developer')], max_length=50)),
                ('profile_picture', models.ImageField(blank=True, default='profile_pics/default-user.png', null=True, upload_to='profile_pics/')),
            ],
        ),
    ]
